name: build-checks-devel

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/r-ver:devel

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update 
          apt-get install -y --no-install-recommends \
            libharfbuzz-dev libfribidi-dev zlib1g-dev libfftw3-dev libxml2-dev \
            libxt-dev curl libglpk-dev libcairo2-dev libmagick++-dev \
            libcurl4-gnutls-dev libudunits2-dev libgdal-dev libproj-dev \
            pandoc libnode-dev tk libv8-dev git \
            cmake libabsl-dev
          apt-get clean
          rm -rf /var/lib/apt/lists/*

      - name: Set Bioconductor and CRAN repos
        run: |
          install.packages("BiocManager")
          options(repos = BiocManager::repositories())
        shell: Rscript {0}

      - name: Install renv and restore packages
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Run R CMD check
        run: |
          install.packages("rcmdcheck")
          rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Run BiocCheck
        run: |
          BiocManager::install("BiocCheck")
          BiocCheck::BiocCheck(".")
        shell: Rscript {0}

      - name: Session info
        run: |
          install.packages("sessioninfo")
          options(width = 100)
          sessioninfo::session_info()
        shell: Rscript {0}
